### ISSUE TITLE
TBD is unsupported by old toolchains – workaround needed

### ISSUE THREAD

**Issue by L45eMy** [theos/theos#167]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)
## What are the steps to reproduce this issue?
1. Create empty project with `nic.pl`
2. `make package`
## What happens?

Build fails.
## What were you expecting to happen?

Build succeeds.
## Any logs, error output, etc?

> Making all for tweak test…
> ==> Linking tweak test (armv7)…
> ld: framework not found CydiaSubstrate
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make[3]: **\* [.theos/obj/debug/armv7/test.dylib] Error 1
> make[2]: **\* [.theos/obj/debug/armv7/test.dylib] Error 2
> make[1]: **\* [internal-library-all_] Error 2
> make: **\* [test.all.tweak.variables] Error 2
## Any other comments?

First occurred after updating Theos from some early 2016 version.
## What versions of software are you using?

**Operating System:** OS X 10.9

**Toolchain Version:** Xcode 6.2, latest Theos

**SDK Version:** 8.2

**Comment by kirb** [comment]
Run `make update-theos` again. Sorry for the trouble.

**Comment by L45eMy** [comment]
Still getting the same error. :-/ Running `make update-theos`, everything seems up to date.

> Updating Theos…
Fetching origin
Already up-to-date.
> Updating submodules…
Entering 'vendor/include'
Entering 'vendor/include/CaptainHook'
Entering 'vendor/include/LightMessaging'
Entering 'vendor/include/libactivator'
Entering 'vendor/include/rocketbootstrap'
Entering 'vendor/include/rocketbootstrap/LightMessaging'
Theos: Already up-to-date.
Entering 'vendor/lib'
> Running post-update configuration…

**Comment by uroboro** [comment]
Does Xcode 6.2 support .tbd files?

**Comment by L45eMy** [comment]
I don't think so, but Xcode 6.2 is the last version to run under Mavericks… Do I have to upgrade to at least Yosemite and Xcode 7? Or is there any older version working with Xcode 6.2?

**Comment by kirb** [comment]
Clang actually supports it as of Xcode 7.0 (iOS SDK 8.0), but enable it
only if you're using iOS SDK 8.4+. I wasn't too sure how it would work out
when I implemented it so I restrained it to the latest SDK at the time. It
certainly could be dropped back to 8.0+.

Of course do also keep in mind Mavericks will become unsupported by Apple
when Sierra is out.

On Fri., 15 Jul. 2016 at 02:12, L45eMy <notifications@github.com> wrote:

> I don't think so, but Xcode 6.2 is the last version to run under
> Mavericks… Do I have to upgrade to at least Yosemite and Xcode 7? Or is
> there any older version working with Xcode 6.2?
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/theos/theos/issues/167#issuecomment-232721860>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAvMvf8dCNuAi-M4BbXEPaX-Mr9IllPEks5qVmbogaJpZM4JFXI3>
> .
>
-- 
Adam Demasi
HASHBANG Productions
hbang.com.au

**Comment by kirb** [comment]
Aah man I confused modules and tbds (and Xcode 7 and 6, apparently). I
don't think Xcode 6 had any support for tbd. Will need to work something
out – an alternate submodule with stub binaries, possibly. Till then you
can just grab frameworks/libs from your device and put them in $THEOS/lib.
On Fri., 15 Jul. 2016 at 14:54, Adam D <kirbylover4000@gmail.com> wrote:

> Clang actually supports it as of Xcode 7.0 (iOS SDK 8.0), but enable it
> only if you're using iOS SDK 8.4+. I wasn't too sure how it would work out
> when I implemented it so I restrained it to the latest SDK at the time. It
> certainly could be dropped back to 8.0+.
>
> Of course do also keep in mind Mavericks will become unsupported by Apple
> when Sierra is out.
>
> On Fri., 15 Jul. 2016 at 02:12, L45eMy <notifications@github.com> wrote:
>
>> I don't think so, but Xcode 6.2 is the last version to run under
>> Mavericks… Do I have to upgrade to at least Yosemite and Xcode 7? Or is
>> there any older version working with Xcode 6.2?
>>
>> —
>> You are receiving this because you commented.
>>
>>
>> Reply to this email directly, view it on GitHub
>> <https://github.com/theos/theos/issues/167#issuecomment-232721860>, or mute
>> the thread
>> <https://github.com/notifications/unsubscribe/AAvMvf8dCNuAi-M4BbXEPaX-Mr9IllPEks5qVmbogaJpZM4JFXI3>
>> .
>>
> --
> Adam Demasi
> HASHBANG Productions
> hbang.com.au
>
-- 
Adam Demasi
HASHBANG Productions
hbang.com.au

**Comment by kirb** [comment]
A thought – Xcode the *app* may not work on Mavericks, but the toolchain might. I do recall myself successfully using Xcode 6.4 with Theos on Mavericks at one point. If you have a moment, try downloading the latest (7.3.1), rename it accordingly, and switch to it:

```console
$ sudo xcode-select --switch /Applications/Xcode-7.3.1.app/Contents/Developer
```

**Comment by L45eMy** [comment]
Thank you very much for you responses.

* Copying CydiaSubstrate from the device into `$THEOS/lib` results in the same error message as in the first post.

* The Xcode 7 toolchain unfortunately does not work on Mavericks, I'm getting the following error:  
    ```
    dyld: Symbol not found: _kSZArchiverOptionNoCentralDirectory
    Referenced from: /Applications/Xcode 7.app/Contents/SharedFrameworks/DVTFoundation.framework/Versions/A/../../..//DVTInstrumentsFoundation.framework/Versions/A/DVTInstrumentsFoundation
    Expected in: /System/Library/PrivateFrameworks/StreamingZip.framework/Versions/A/StreamingZip
    in /Applications/Xcode 7.app/Contents/SharedFrameworks/DVTFoundation.framework/Versions/A/../../..//DVTInstrumentsFoundation.framework/Versions/A/DVTInstrumentsFoundation
    make: error: unable to locate xcodebuild, please make sure the path to the Xcode folder is set correctly!
    make: error: You can set the path to the Xcode folder using /usr/bin/xcode-select -switch
    ```

* Xcode 7.3.1 on El Capitan works.

**Comment by kirb** [comment]
Ah man, that's disappointing. The first one in particular sounds like a limitation of the old toolchain, so you'd probably have to copy the `CydiaSubstrate` binary to `vendor/lib/CydiaSubstrate.framework`. Sounds like we'll have to re-add stub binaries.

**Comment by L45eMy** [comment]
Copying the `CydiaSubstrate` binary to `vendor/lib/CydiaSubstrate.framework` solves the problem.

**Comment by kirb** [comment]
Since this I’ve changed stance and decided that we shouldn’t work around this – users on older toolchains can grab binaries from their device or by extracting from debs. This was how it worked previously anyway, so I don’t think it’s much of an inconvenience to worry about.

**Comment by Leeksov** [comment]
I add this binary, but same error
