### ISSUE TITLE
Can not install theos to ios by following the instructions.

### ISSUE THREAD

**Issue by lyqflnh** [theos/theos#370]
16G iPhone 5s 8.4 with TaiG Untether JailBreak 
32G iPhone 5s 9.1 with Pangu Untether JailBreak have the same problem

When I follow this step: 

`git clone --recursive https://github.com/theos/theos.git $THEOS`

I got this:

```
iPhone-5s:~ root# git clone --recursive https://github.com/theos/theos.git $THEOS
Cloning into 'theos'...
remote: Enumerating objects: 40, done.
remote: Counting objects: 100% (40/40), done.
remote: Compressing objects: 100% (25/25), done.
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /usr/libexec/git-core/git
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /usr/libexec/git-core/git
  Expected in: /usr/lib/libSystem.B.dylib

error: index-pack died of signal 5
fatal: index-pack failed
```

**Comment by kirb** [comment]
What repo is git installed from?

**Comment by kirb** [comment]
Any idea @sbingner?

**Comment by uroboro** [comment]
Not a core issue but the instructions say not to use root while installing Theos.

**Comment by lyqflnh** [comment]
I use the mobile user, same issue

```
iphone-5s:~ mobile$ git clone --recursive https://github.com/theos/theos.git ~/theos
Cloning into '/var/mobile/theos'...
remote: Enumerating objects: 40, done.
remote: Counting objects: 100% (40/40), done.
remote: Compressing objects: 100% (25/25), done.
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /usr/libexec/git-core/git
  Expected in: dyld shared cache

dyld: Symbol not found: _clock_gettime
  Referenced from: /usr/libexec/git-core/git
  Expected in: dyld shared cache

error: index-pack died of signal 5
fatal: index-pack failed
```

I use a root user with iPhone 8plus 11.2.5 and follow the instructions, there is no problem. but that's not my iPhone😂

I wonder maybe the git I downloaded is still not compatible, since @sbingner said it is not test in every iOS.

**Comment by uroboro** [comment]
It probably is a git issue. This also happened with a previous version when tested on an iPhone 5 on iOS 6.

**Comment by sbingner** [comment]
If you add apt.bingner.com and update to those you should be good.  I’ll look at fixing the copies on that repo later today.

**Comment by sbingner** [comment]
I just updated repo.bingner.com with a git that doesn't use clock_gettime - tested it on iOS 9.0.1 and it worked

**Comment by lyqflnh** [comment]
I use following commands which are from another issue to avoid the git problem

```
$ git clone --recursive https://github.com/theos/theos.git
$ rsync -aP theos/ root@youriphone:/var/theos
```

And I just test new git, it works on my iPhone 5s with 8.4, 9.1 and 9.3.3. @sbingner

**Comment by kirb** [comment]
Closing as this should be fixed.
