### ISSUE TITLE
Standalone use of toolchain with 14.4 SDK results in linker errors

### ISSUE THREAD

**Issue by sherrellbc** [theos/theos#586]
What are the steps to reproduce this issue?
-------------------------------------------
1. Attempt to use the toolchain standalone from the cmdline

Create simple file /tmp/a.c
```
#include <stdio.h>

int main(void)
{
    printf("Hello, World!\n");
    return 0;
}
```
```
# $THEOS/toolchain/bin/arm64-apple-darwin14-clang -B/opt/theos/toolchain/bin -isysroot /tmp/sdks/iPhoneOS14.4.sdk -arch arm64 /tmp/a.c -o /tmp/a
```

What happens?
-------------
Linker claims desired architecture is different from architecture of related tbd file.

What were you expecting to happen?
----------------------------------
Successful compilation. It seems to work fine with current SDK `iPhoneOS10.3.sdk`, but not any of the others. It used to work with the previous `iPhoneOS11.2.sdk` as well.

Any logs, error output, etc?
----------------------------
```
ld: warning: ignoring file /tmp/sdks/iPhoneOS14.4.sdk/usr/lib/libSystem.tbd, file was built for unsupported file format ( 0x2D 0x2D 0x2D 0x20 0x21 0x74 0x61 0x70 0x69 0x2D 0x74 0x62 0x64 0x0A 0x74 0x62 ) which is not the architecture being linked (arm64): /tmp/sdks/iPhoneOS14.4.sdk/usr/lib/libSystem.tbd
Undefined symbols for architecture arm64:
  "_printf", referenced from:
      _main in a-317fd0.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Comments
-----------
Toolchain and SDKs pulled from installation instructions: https://github.com/theos/theos/wiki/Installation-Linux

I noticed that the SDK file `usr/libSystem.B.tbd` (and likely all/most tbd files) have change quite a bit. In particular architectures now appear to be suffixed with "-ios"

```
targets:         [ armv7-ios, armv7s-ios, arm64-ios, arm64e-ios ]
```

But generally the issue seems to be that the linker is not properly interpreting the tbd files, since it is clearly reading the header assuming it is an object type.

What versions of software are you using?
----------------------------------------
**Operating System:** OSX

**Toolchain Version:** Latest

**SDK Version:** Latest (14.4 specifically)

**Comment by kabiroberai** [comment]
The error message here is misleading. If you decode the initial hex bytes in the error message they translate to `-- !tapi-tbd`. The linker thinks the file is a MachO and is trying to parse the first few bytes as a magic constant, because it doesn't recognise the tbd v4 header. In summary, this just means you're using a toolchain that's too old for the 14.4 sdk. The recommended solution atm is to use sbingner's toolchain instead: see #551.

**Comment by UsrLightmann** [comment]
Bingner's toolchain won't work for 14 sdks. You'll want to use [CRKatri's](https://github.com/CRKatri/llvm-project/releases/tag/swift-5.3.2-RELEASE). See [here](https://github.com/theos/theos/issues/551#issuecomment-808965627)
